# This is part - 2 of the solution

### This section of the solution shows the graphical visualizations of the heatmaps

### Contents

1. Imports 
2. Visualizations

    2.a- Current Address Heatmaps
    
    2.b- Permanent Address Heatmaps

** Importing Necessary Packages for the Google Maps API usage **

In [34]:
import gmaps
import gmaps.datasets
import pandas as pd
gmaps.configure(api_key='AIzaSyCKwsbD8w1JruqmasExy9wkPnU8vvqifXY') # Your Google API key

# load a Numpy array of (latitude, longitude) pairs
locations = gmaps.datasets.load_dataset("taxi_rides")

fig = gmaps.figure()
fig.add_layer(gmaps.heatmap_layer(locations))
fig

Figure(layout=FigureLayout(height='420px'))

In [2]:
from matplotlib.cm import viridis
from matplotlib.colors import to_hex

import gmaps
import gmaps.datasets
import gmaps.geojson_geometries

gmaps.configure(api_key='AIzaSyCKwsbD8w1JruqmasExy9wkPnU8vvqifXY') # Your Google API key

countries_geojson = gmaps.geojson_geometries.load_geometry('countries') # Load GeoJSON of countries

rows = gmaps.datasets.load_dataset('gini') # 'rows' is a list of tuples
country2gini = dict(rows) # dictionary mapping 'country' -> gini coefficient
min_gini = min(country2gini.values())
max_gini = max(country2gini.values())
gini_range = max_gini - min_gini

def calculate_color(gini):
    """
    Convert the GINI coefficient to a color
    """
    # make gini a number between 0 and 1
    normalized_gini = (gini - min_gini) / gini_range

    # invert gini so that high inequality gives dark color
    inverse_gini = 1.0 - normalized_gini

    # transform the gini coefficient to a matplotlib color
    mpl_color = viridis(inverse_gini)

    # transform from a matplotlib color to a valid CSS color
    gmaps_color = to_hex(mpl_color, keep_alpha=False)

    return gmaps_color

# Calculate a color for each GeoJSON feature
colors = []
for feature in countries_geojson['features']:
    country_name = feature['properties']['name']
    try:
        gini = country2gini[country_name]
        color = calculate_color(gini)
    except KeyError:
        # no GINI for that country: return default color
        color = (0, 0, 0, 0.3)
    colors.append(color)

fig = gmaps.figure()
gini_layer = gmaps.geojson_layer(
    countries_geojson,
    fill_color=colors,
    stroke_color=colors,
    fill_opacity=0.8)
fig.add_layer(gini_layer)
fig

Figure(layout=FigureLayout(height='420px'))

** Reading the data to be plotted **

In [6]:
df1=pd.read_csv('processed_data2.csv')

In [7]:
df1.head()

,cust_id_token,current_address3,current_city,current_state,current_pin_code,permanent_address3,permanent_city,permanent_state,permanent_pin_code,current_latitude,current_longitude,permanent_latitude,permanent_longitude
0,1,NaN,JAMBI,INDONESIA,36126,NaN,CHENNAI,TAMIL NADU,600029,-1.611572,102.779699,13.080172,80.283833
1,2,INJAMBAKKAM,CHENNAI,TAMIL NADU,600115,NaN,LONDON,MIDDLE SEX,HA047H,13.080172,80.283833,51.507322,-0.127647
2,3,ROODEPOORT,JOHANNESBURG,GAUTENG,2169,MANDIR RMC GARDEN,PUNE,MAHARASHTRA,412207,-26.205000,28.049722,18.520306,73.854319
3,4,NaN,DUBAI,DUBAI,18582,NaN,BARODA,GUJARAT,390007,25.075010,55.188761,41.957025,-86.484348
4,5,NaN,SIRSA,HARYANA,125055,NaN,SIRSA,HARYANA,125055,29.583333,75.083333,29.583333,75.083333

** We only need the lat and long to plot the heatmap on the map. **

In [12]:
temp=df1[['current_latitude','current_longitude']]

In [22]:
temp2=df1[['permanent_latitude','permanent_longitude']]

In [13]:
temp

    current_latitude  current_longitude
0          -1.611572         102.779699
1          13.080172          80.283833
2         -26.205000          28.049722
3          25.075010          55.188761
4          29.583333          75.083333
5          18.938771          72.835335
6          27.101841          93.629212
7          26.838100          80.934600
8         -33.795275         151.011665
9          25.451942          56.356393
10         18.520306          73.854319
11         19.201561          73.200477
12         28.464615          77.029919
13         18.938771          72.835335
14         39.906217         116.391276
15         30.909016          75.851601
16         23.654434          86.145644
17         27.101841          93.629212
18         27.487972          95.360186
19         49.112952           7.316224
20         22.297076          73.195737
21         18.938771          72.835335
22          0.000000           0.000000
23         19.697875          72.768694
24         34.111223         -82.867084
25         18.938771          72.835335
26         18.938771          72.835335
27         18.938771          72.835335
28         18.933267          72.834515
29         19.697875          72.768694
..               ...                ...
70         51.271532          -0.341452
71         22.500000          83.500000
72         24.883716          74.624415
73         18.938771          72.835335
74         22.116667          78.800000
75         29.963744          77.542746
76         15.857267          74.506934
77         15.857267          74.506934
78         28.614179          77.202266
79         18.520306          73.854319
80         18.520306          73.854319
81         22.762300          78.349500
82         23.000000          76.166667
83         12.007410          79.087219
84         31.532852          75.902548
85         31.532852          75.902548
86         18.938771          72.835335
87         20.952407          72.932383
88         28.651718          77.221939
89         18.520306          73.854319
90         31.814215          75.657759
91         32.921973          75.133148
92         36.701463        -118.755997
93         32.701939         -97.105625
94         31.844233          74.762523
95         26.304000          50.196024
96          0.000000           0.000000
97         27.890066          76.285823
98         24.148333          47.305000
99         31.332376          75.576889

[100 rows x 2 columns]

### The below is the output of the heatmap graph of current address.

In [33]:
fig1 = gmaps.figure()
fig1.add_layer(gmaps.heatmap_layer(temp))
#fig1.add_layer(starbucks_layer)
#fig1.add_layer(gmaps.heatmap_layer(temp2))
fig1.gradient = ['white', 'gray']
fig1

Figure(layout=FigureLayout(height='420px'))

** Use ctrl + scroll to zoom in/out on the map**

### Location of the permanent address

In [31]:
import gmaps
import gmaps.datasets
gmaps.configure(api_key='AIzaSyCKwsbD8w1JruqmasExy9wkPnU8vvqifXY') # Your Google API key

#df = gmaps.datasets.load_dataset_as_df('starbucks_kfc_uk')

#starbucks_df = df[df['chain_name'] == 'starbucks']
dfx = temp2

starbucks_layer = gmaps.symbol_layer(
    dfx, fill_color="green", stroke_color="green", scale=2
)
fig = gmaps.figure()
fig.add_layer(starbucks_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Heatmap of the Permanent Addresses

In [35]:
fig1 = gmaps.figure()
fig1.add_layer(gmaps.heatmap_layer(temp2))
#fig1.add_layer(starbucks_layer)
#fig1.add_layer(gmaps.heatmap_layer(temp2))
fig1.gradient = ['white', 'gray']
fig1

Figure(layout=FigureLayout(height='420px'))

## It can be observed that there is more heat on (depicted by dark shades of green and red) India as permanent Address, compared to the current Address.

## This could imply that lot of people have been moving abroad, and working there